apiVersion: v1
kind: Pod
metadata:
  name: mithun1
  labels:
    app: mithun1
spec:
  tolerations:  # ✅ Changed from 'toleration' to 'tolerations'
    - key: "type"
      operator: "Equal"  # ✅ Changed 'equal' to 'Equal' (case-sensitive)
      value: "gpn"
      effect: "NoSchedule"
  containers: 
    - name: mithun1
      image: user/mithun1:v1
      ports:
        - containerPort: 8080
