apiVersion: v1
kind: Pod
metadata:
  name: mithun1
  labels:
    app: mithun1
spec:
  toleration:
  - key: "type"
    operator: "equal"
    value: "gpn"
    effect: "NoSchedule"
  containers: 
   - name: mithun1
     image: user/mithun1:v1
     ports:
       - containerPort: 8080    