name: set-up hpa

on:
  workflow_dispatch

jobs:
  create-hpa:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      # Step 2: Azure Portal Login
      - name: Login to Azure
        run: az login --use-device-code  

      # Step 3: Set AKS Context
      - name: Set AKS Context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.Resource_Group }} 
          cluster-name: ${{ secrets.AKS_NAME }}

        #  step4: deploy hpa configuration
      - name: apply hpa
        run: |
         kubectl apply -f aks/hpa-cluster.yml

        #  step5: check the hpa configuration
      - name: check hpa
        run: |
         kubectl het hpa -n github-runner

        #  step6: monitor hpa config
      - name: monitor hpa config
        run: |
         kubectl get po -n github-runner -w            


