name: aks deployment

on:
  workflow_dispatch

jobs:
  create-aks:
    runs-on: ubuntu-latest
    steps:

        # step1: checkout code
      - name: checkour repository
        uses: actions/checkout@v4
 
        # step2: azure portal login
      - name: Login azure
        run: az login --use-device-code  

        # step3: create resource group
      - name: create Resource Group
        run: |
          az group create --name ${{ secrets.Resource_group }} --location ${{ secrets.location }} 

        # step4: create aks cluster
      - name: aks cluster
        run: |
          az aks create --resource-group ${{ secrets.Resource_Group }} --name ${{ secrets.aks_name }} --location ${{ secrets.location }} --node-count 1 --generate-ssh-key 

        # step5: get aks credentials
      - name: aks credentials
        run: |
          az aks get credentials --resource-group ${{ secrets.Resource_Group }}  --name ${{ secrets.aks_name }}  

        # step6: verify aks cluster
      - name: verify aks cluster
        run: |
          kubectl get nodes
          kubectl get namespace    
