name: set-up hpa

on:
  workflow_dispatch

jobs:
  create-hpa:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4
 
        # step2: use manage identity
      - name: Login to Azure # Azure Login with User Managed Identity
        uses: azure/login@v2
        with:
          auth-type: Identity
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set AKS Context
      - name: Set AKS Context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.Resource_Group }} 
          cluster-name: ${{ secrets.AKS_NAME }}

