name: aks set-up

on:
  workflow_dispatch

jobs:
  create-aks:
    runs-on: ubuntu-latest
    steps:

        # step1: checkout code
      - name: checkour repository
        uses: actions/checkout@v4
 
        # step2: azure portal login
      - name: Login azure
        run: az login --use-device-code  

        # step3: set aks context
      - name: set aks context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
         resource-group: ${{ secrets.Resource_Group }} 
         cluster-name: ${{ secrets.AKS_NAME }}

      # Step 4: Apply taint to a node
      - name: Taint AKS Node
        run: |
          NODE_NAME=$(kubectl get nodes -o jsonpath='{.items[0].metadata.name}')
          kubectl taint nodes $NODE_NAME type=gpn:NoSchedule --overwrite

      # Step 5: Deploy appone and apptwo with tolerations
      - name: Deploy appone and apptwo to AKS
        run: |
          kubectl apply -f aks/appone.yaml
          kubectl apply -f aks/apptwo.yaml       

        # Step6: verify taint
      - name: Verify Taint
        run: |
          kubectl describe node $GITHUB_RUNNER_NODE | grep Taints
          
        # step7: verify pod status         
      - name: Verify Pod Placement
        run: |
          kubectl get pods -o wide



      
