name: aks set-up

on:
  workflow_dispatch

jobs:
  create-aks:
    runs-on: ubuntu-latest
    steps:

        # step1: checkout code
      - name: checkour repository
        uses: actions/checkout@v4
 
        # step2: azure portal login
      - name: Login azure
        run: az login --use-device-code  

        # step3: set aks context
      - name: set aks context
        id: set-context
        uses: azure/set-aks-context@v3
        with:
         resource-group: ${{ secrets.Resource_Group }} 
         cluster-name ${{ secrets.AKS_NAME }}

          step4: verify cluster
      - name: verify cluster
        run: |
          kubectl get nodes
          kubectl get namespace        
